### ISSUE TITLE
The heading on the "Create Course" page displays as "Create Workshop"

### ISSUE THREAD

**Issue by taufma8** [treehouse-apprenticeship/athena_irv_team2#1]
Need to update the "Create Course" page header to display "Create Course" instead of "Create Workshop".

_Steps to Reproduce_
Using the React client, click on the "Sign In" link displayed in the header to browse to the "Sign In" page.
Sign in using Joe's user information.
Email Address: joe@smith.com
Password: joepassword
From the Course List page (i.e. the "Home" page), click on the "New Course" card to browse to the Create Course page.
Notice that the page heading displays as "Create Workshop".
The page heading should display as "Create Course".

**Comment by Venoox** [comment]
Fixed in #10
