### ISSUE TITLE
The "Materials Needed" section doesn't display on the Course Detail page

### ISSUE THREAD

**Issue by taufma8** [treehouse-apprenticeship/athena_irv_team2#4]
When viewing the Build a Basic Bookcase course, the "Materials Needed" section doesn't display.

**Steps to Reproduce**

Using the React client, browse to the "Build a Basic Bookcase" course's Course Detail page.
Notice that the course's content for the "Materials Needed" section doesn't display.
You can use the React Developer Tools to confirm that the CourseDetail React component state contains an object whose materialsNeeded property is set to a non-null, non-empty value.

**Comment by youtr5r** [comment]
Issue has been resolved
